### ISSUE TITLE
Better on one line

### ISSUE THREAD

**Issue by uwe-007** [1Tech-X/termux-PS1#1]
PS1 with two lines could lead to problems (I had one with ytfzf), so I changed it to ("\n" was added):

`export PS1='\033[01;34m\]┌──\[\033[01;32m\]root\[\033[01;34m\]@\[\033[01;31m\]\h\[\033[00;34m\]\[\033[01;34m\]\w\[\033[00;34m\]\[\033[01;32m\]:\n\[\033[01;34m\]└╼\[\033[01;31m\]►\[\033[01;32m\]'`

**Comment by 1Tech-X** [comment]
Thanks
